import React from "react";
import { Hammer, Sparkles, CheckCircle2 } from "lucide-react";
import { FeatureItem, StatItem, GalleryCardConfig } from "./types";

export const STATEMENT_WORDS = [
  "Tadiks",
  "Cleaning",
  "&",
  "Bau",
  "vereint",
  "meisterhaften",
  "Innenausbau",
  "und",
  "zertifizierte",
  "Gebäudereinigung",
  "in",
  "Chemnitz",
  "–",
  "für",
  "bezugsfertige",
  "Perfektion",
  "und",
  "dauerhaften",
  "Werterhalt",
  "nahtlos",
  "aus",
  "einer",
  "Hand.",
];

export const GALLERY_CARDS: GalleryCardConfig[] = [
  {
    id: 1,
    wrapperClass: "card-wrapper-1 absolute left-0 sm:left-1 lg:left-2 xl:left-3 top-0 z-30 pointer-events-none will-change-transform",
    maskClass: "card-mask-1",
    imageClass: "card-img-1",
    aspectClass: "aspect-[3/4]",
    widthClass: "w-[210px] sm:w-[250px] lg:w-[280px]",
    initialClipPath: "inset(100% 100% 0% 0% round 4px)",
    finalClipPath: "inset(0% 0% 0% 0% round 4px)",
    src: "/images/about_gallery_1.webp",
    alt: "Meisterhafte Badsanierung und makellose Hygiene Chemnitz",
    sizes: "(max-width: 768px) 250px, 280px",
    startTime: 0.05,
    duration: 0.52,
    parallaxY: 26,
    parallaxScale: 1.36,
  },
  {
    id: 2,
    wrapperClass: "card-wrapper-2 absolute right-0 sm:right-1 lg:right-2 xl:right-3 top-0 z-30 pointer-events-none will-change-transform",
    maskClass: "card-mask-2",
    imageClass: "card-img-2",
    aspectClass: "aspect-square",
    widthClass: "w-[180px] sm:w-[220px] lg:w-[250px]",
    initialClipPath: "inset(100% 0% 0% 100% round 4px)",
    finalClipPath: "inset(0% 0% 0% 0% round 4px)",
    src: "/images/about_gallery_2.webp",
    alt: "Architektonische Details und natürliche Ruhe",
    sizes: "(max-width: 768px) 220px, 250px",
    startTime: 0.08,
    duration: 0.52,
    parallaxY: 20,
    parallaxScale: 1.30,
  },
  {
    id: 3,
    wrapperClass: "card-wrapper-3 absolute left-1/2 top-0 z-30 pointer-events-none will-change-transform",
    maskClass: "card-mask-3",
    imageClass: "card-img-3",
    aspectClass: "aspect-[16/9]",
    widthClass: "w-[340px] sm:w-[480px] lg:w-[600px] xl:w-[660px]",
    initialClipPath: "inset(100% 100% 0% 0% round 4px)",
    finalClipPath: "inset(0% 0% 0% 0% round 4px)",
    src: "/images/about_gallery_3.webp",
    alt: "Schlüsselfertige Sanierung und bezugsfertige Bauendreinigung in Chemnitz",
    sizes: "(max-width: 768px) 480px, 660px",
    startTime: 0.28,
    duration: 0.54,
    isCenter: true,
    parallaxY: 32,
    parallaxScale: 1.42,
  },
  {
    id: 4,
    wrapperClass: "card-wrapper-4 absolute left-1 sm:left-3 lg:left-5 xl:left-7 top-0 z-30 pointer-events-none will-change-transform",
    maskClass: "card-mask-4",
    imageClass: "card-img-4",
    aspectClass: "aspect-square",
    widthClass: "w-[180px] sm:w-[220px] lg:w-[250px]",
    initialClipPath: "inset(100% 100% 0% 0% round 4px)",
    finalClipPath: "inset(0% 0% 0% 0% round 4px)",
    src: "/images/about_gallery_4.webp",
    alt: "Präzises Bauhandwerk und Wasserwaagen-Justierung",
    sizes: "(max-width: 768px) 220px, 250px",
    startTime: 0.44,
    duration: 0.52,
    parallaxY: 22,
    parallaxScale: 1.32,
  },
  {
    id: 5,
    wrapperClass: "card-wrapper-5 absolute right-1 sm:right-3 lg:right-5 xl:right-7 top-0 z-30 pointer-events-none will-change-transform",
    maskClass: "card-mask-5",
    imageClass: "card-img-5",
    aspectClass: "aspect-[3/4]",
    widthClass: "w-[210px] sm:w-[250px] lg:w-[280px]",
    initialClipPath: "inset(100% 0% 0% 100% round 4px)",
    finalClipPath: "inset(0% 0% 0% 0% round 4px)",
    src: "/images/about_gallery_5.webp",
    alt: "Streifenfreie Fenster- und Glasfassadenreinigung Chemnitz",
    sizes: "(max-width: 768px) 250px, 280px",
    startTime: 0.48,
    duration: 0.52,
    parallaxY: 28,
    parallaxScale: 1.38,
  },
];

export const FEATURES_DATA: FeatureItem[] = [
  {
    num: "01",
    icon: <Hammer className="w-5 h-5 text-brand-navy" />,
    title: "Bau, Sanierung & Innenausbau",
    desc: "Fachgerechter Trockenbau, Akustik- & Brandschutz, meisterhafte Q1–Q4 Spachtel- und Malerarbeiten sowie schlüsselfertige Komplettsanierungen für Wohnungen und Gewerbeobjekte in Chemnitz.",
  },
  {
    num: "02",
    icon: <Sparkles className="w-5 h-5 text-brand-navy" />,
    title: "Zertifizierte Gebäudereinigung",
    desc: "Hygienische Unterhaltsreinigung für Praxen und Büros, streifenfreie Glas- und Fensterreinigung sowie bezugsfertige Bauendreinigungen mit modernen Kärcher-Systemen und Umweltzertifikat.",
  },
  {
    num: "03",
    icon: <CheckCircle2 className="w-5 h-5 text-brand-navy" />,
    title: "Schlüsselfertig aus einer Hand",
    desc: "Keine Schnittstellenverluste zwischen Handwerkern und Reinigungsteams. Feste deutsche Objektleiter, verbindliche Festpreise und garantierte Termintreue in ganz Sachsen.",
  },
];

export const STATS_DATA: StatItem[] = [
  {
    target: 5,
    suffix: "+",
    label: "Jahre Meistererfahrung",
    sublabel: "Fachbetrieb in Chemnitz & Region",
  },
  {
    target: 103,
    suffix: "+",
    label: "Realisierte Projekte",
    sublabel: "Wohn-, Gewerbe- & Praxisobjekte",
  },
  {
    target: 100,
    suffix: "%",
    label: "Garantierte Termintreue",
    sublabel: "Feste Zeitpläne für Bau & Reinigung",
  },
  {
    target: 94,
    suffix: "%",
    label: "Kundenzufriedenheit",
    sublabel: "Verifizierte Kundenbewertungen",
  },
];
